openapi: 3.0.0
info:
  title: POC API
  description: This is the OpenAPI Schema for POC.
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: LocalRun
paths:
  /users/{userId}:
    get:
      operationId: getUsers
      summary: Returns a user by ID.
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user to return.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: A user object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: The specified user ID is invalid (not a number).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericError'
        '404':
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error
  /users:
    post:
      operationId: addUsers
      summary: Add a user
      requestBody:
        description: User data to add
        required: true
        content:
          application/json:
            schema:
              type: object
              description: polymorphism object for user data
      responses:
        '204':
          description: No Content if success
        default:
          description: Unexpected Error
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
          example: Jessica Smith
        age:
          type: integer
          format: int32
          example: 4
          minimum: 0
        email:
          type: string
          format: email
          example: 123@gmail.com
    UserResponse:
      allOf:
        - $ref: '#/components/schemas/GenericApiResponse'
        - properties:
            data:
              $ref: '#/components/schemas/User'
    GenericError:
      description: Error message response
      $ref: '#/components/schemas/GenericApiResponse'
    GenericApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string
        developerMessage:
          type: string
      required:
        - code
        - message
        - developerMessage