openapi: 3.0.0
info:
  title: POC API
  description: This is the OpenAPI Schema for HSBC-Mandate POC.
  version: 0.0.1
servers:
  - url: localhost:8080
    description: LocalRun
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
paths:
  /users/{userId}:
    get:
      summary: Returns a user by ID.
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the user to return.
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: A user object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                    example: 4
                  name:
                    type: string
                    example: Jessica Smith
        '400':
          description: The specified user ID is invalid (not a number).
        '404':
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error
